/**
 * env.js — Runtime environment configuration for CloudSentinel
 *
 * Auto-generated by deploy_console.py on 2026-05-09 11:02 UTC
 * Re-run deploy_console.py to regenerate this file after infrastructure changes.
 *
 * NEVER commit real credentials or secrets here.
 * These are non-secret deployment outputs safe to store in source control.
 */

window.ENV_COGNITO_POOL_ID   = "us-east-1_CVp34GQnU";
window.ENV_COGNITO_CLIENT_ID = "62ng74bnri2bblaskfd8rik293";
window.ENV_API_URL            = "https://x90odq92q5.execute-api.us-east-1.amazonaws.com/dev";
window.ENV_REGION             = "us-east-1";
window.ENV_CFN_TEMPLATE_URL   = "https://cloudsentinel-cf-templates-871070087236.s3.amazonaws.com/scanner-role.yaml";
window.ENV_LAMBDA_ROLE_ARN    = "arn:aws:iam::871070087236:role/cloudsentinel-lambda-role";
