#!/usr/bin/env python3
"""
post_deploy.py — CloudSentinel post-deployment configurator
------------------------------------------------------------
Run this ONCE after every `terraform apply` to:
  1. Read all Terraform outputs
  2. Write modules/frontend/js/env.js with real values
  3. Upload scanner-role.yaml to the S3 artifacts bucket

Usage:
    python post_deploy.py

Requirements:
    pip install boto3
    AWS CLI must be configured with the same account/region used for terraform apply
"""

import json
import os
import subprocess
import sys
import boto3

# ── Paths (relative to project root) ─────────────────────────────────────────
ROOT = os.path.dirname(os.path.abspath(__file__))
TF_DIR = os.path.join(ROOT, "infrastructure", "terraform")
ENV_JS = os.path.join(ROOT, "modules", "frontend", "js", "env.js")
CFN_TEMPLATE = os.path.join(ROOT, "infrastructure", "cloudformation", "scanner_role.yaml")


def get_terraform_outputs():
    """Run terraform output -json and return a dict of output values."""
    print("Reading Terraform outputs...")
    result = subprocess.run(
        ["terraform", "output", "-json"],
        cwd=TF_DIR,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"ERROR: terraform output failed:\n{result.stderr}")
        sys.exit(1)
    raw = json.loads(result.stdout)
    # Unwrap {value: ..., type: ...} structure
    return {k: v["value"] for k, v in raw.items()}


def write_env_js(outputs):
    """Write modules/frontend/js/env.js from Terraform outputs."""
    pool_id     = outputs.get("cognito_user_pool_id", "")
    client_id   = outputs.get("cognito_client_id", "")
    api_url     = outputs.get("api_invoke_url", "")
    bucket      = outputs.get("artifacts_bucket", "")
    region      = outputs.get("aws_region", "us-east-1")
    role_arn    = outputs.get("lambda_role_arn", "")

    # Derive account ID from the Lambda role ARN
    account_id = role_arn.split(":")[4] if role_arn and role_arn.startswith("arn:") else ""

    # S3 URL for the CloudFormation scanner role template
    cfn_url = (
        f"https://{bucket}.s3.{region}.amazonaws.com/templates/scanner-role.yaml"
        if bucket else ""
    )

    content = f"""\
/**
 * env.js — CloudSentinel runtime configuration
 *
 * AUTO-GENERATED by post_deploy.py — do NOT edit manually.
 * Re-run `python post_deploy.py` after every `terraform apply`.
 */

window.ENV_COGNITO_POOL_ID     = "{pool_id}";
window.ENV_COGNITO_CLIENT_ID   = "{client_id}";
window.ENV_API_URL             = "{api_url}";
window.ENV_REGION              = "{region}";
window.ENV_CFN_TEMPLATE_URL    = "{cfn_url}";
window.ENV_PLATFORM_ACCOUNT_ID = "{account_id}";
window.ENV_LAMBDA_ROLE_NAME    = "cloudsentinel-lambda-role";
"""
    with open(ENV_JS, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"[OK] env.js written -> {ENV_JS}")
    print(f"   Pool ID  : {pool_id}")
    print(f"   Client ID: {client_id}")
    print(f"   API URL  : {api_url}")
    print(f"   Region   : {region}")
    print(f"   CFN URL  : {cfn_url}")


def upload_cfn_template(outputs):
    """Upload scanner-role.yaml to the S3 artifacts bucket under /templates/."""
    bucket = outputs.get("artifacts_bucket", "")
    region = outputs.get("aws_region", "us-east-1")

    if not bucket:
        print("[WARN]  No artifacts_bucket in outputs -- skipping CFN template upload.")
        return

    if not os.path.exists(CFN_TEMPLATE):
        print(f"[WARN]  CFN template not found at {CFN_TEMPLATE} -- skipping upload.")
        return

    print(f"Uploading scanner-role.yaml -> s3://{bucket}/templates/scanner-role.yaml ...")
    s3 = boto3.client("s3", region_name=region)
    s3.upload_file(
        CFN_TEMPLATE,
        bucket,
        "templates/scanner-role.yaml",
        ExtraArgs={"ContentType": "application/x-yaml"},
    )
    print("[OK] CFN template uploaded.")


def print_summary(outputs):
    print("\n" + "=" * 60)
    print("CloudSentinel deployment complete!")
    print("=" * 60)
    print(f"  API URL      : {outputs.get('api_invoke_url', 'N/A')}")
    print(f"  Cognito Pool : {outputs.get('cognito_user_pool_id', 'N/A')}")
    print(f"  Amplify URL  : {outputs.get('amplify_default_domain', 'N/A')}")
    print(f"  SNS Topic    : {outputs.get('sns_alerts_topic_arn', 'N/A')}")
    print(f"  Step Fn      : {outputs.get('step_function_name', 'N/A')}")
    print("=" * 60)
    print("\n[WARN]  Check your email and confirm the SNS subscription to receive alerts.")
    print("=" * 60 + "\n")


def main():
    outputs = get_terraform_outputs()
    write_env_js(outputs)
    upload_cfn_template(outputs)
    print_summary(outputs)


if __name__ == "__main__":
    main()
